### ISSUE TITLE
按照您的教程，gallery页面无法打开啊。

### ISSUE THREAD

**Issue by GoblinLaboratory** [miccall/hexo-theme-Mic_Theme#49]
还有demo的图片页面也是无法打开。

**Comment by GoblinLaboratory** [comment]
这是log：
Unhandled rejection TypeError: G:\Blog\hexo\blog\themes\Mic\layout\layout.ejs:16
    14|     <% if(page.layout === 'gallery') { %>
    15|         
 >> 16|         <%- partial('_widget/page-gallery', {}, {cache: true}) %>
    17|
    18|     <% } else { %>
    19|                 <%- body %>

G:\Blog\hexo\blog\themes\Mic\layout\_widget\page-gallery.ejs:11
    9|                                          <p><%-theme.Gallery.description %>    author : <a href="<%- config.root%>" style="border-bottom: none;"><%- config.author%></a></p>
    10|                                                 <ul class="gallery_icons">
 >> 11|                             <% if(theme.Nav.icon.github.use === true) { %>
    12|                                 <li><a href="<%= theme.Nav.icon.github.link %>" class="gallery_icon fa-github"><span class="label">GitHub</span></a></li>
    13|                             <% } %>
    14|                             <% if(theme.Nav.icon.Facebook.use === true) { %>

Cannot read property 'github' of undefined
    at eval (eval at compile (G:\Blog\hexo\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:21:26)
    at returnedFn (G:\Blog\hexo\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (G:\Blog\hexo\blog\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (G:\Blog\hexo\blog\node_modules\hexo\lib\theme\view.js:48:23)
    at fragment_cache (G:\Blog\hexo\blog\node_modules\hexo\lib\plugins\helper\partial.js:36:52)
    at Object.fragmentCache (G:\Blog\hexo\blog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.wrapper [as fragment_cache] (G:\Blog\hexo\blog\node_modules\lodash\lodash.js:4949:19)
    at Object.partial (G:\Blog\hexo\blog\node_modules\hexo\lib\plugins\helper\partial.js:36:17)
    at Object.wrapper [as partial] (G:\Blog\hexo\blog\node_modules\lodash\lodash.js:4949:19)
    at eval (eval at compile (G:\Blog\hexo\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:38:17)
    at returnedFn (G:\Blog\hexo\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (G:\Blog\hexo\blog\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (G:\Blog\hexo\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (G:\Blog\hexo\blog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (G:\Blog\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Blog\hexo\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\Blog\hexo\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\Blog\hexo\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\Blog\hexo\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (G:\Blog\hexo\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (G:\Blog\hexo\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (G:\Blog\hexo\blog\node_modules\bluebird\js\release\async.js:17:14)

**Comment by xzy103** [comment]
同问

**Comment by jack870131** [comment]
同問!

**Comment by jack870131** [comment]
@miccall

**Comment by miccall** [comment]
@jack870131  @xzy103  @GoblinLaboratory 
这是个bug ，现在 BUG 已经修复 ，重新下载主题试试
